services:
  crud-api:
    build:
      context: .
      dockerfile: ./src/products/Dockerfile
      target: development
    command: npm run start:dev
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
  mysql:
    image: mysql
    env_file:
      - .env
    ports:
      - '3306:3306'
